name: CI-Analysis

on:
    workflow_dispatch:
    workflow_run:
        workflows: [ "CI" ]
        types:
            - completed

jobs:
    mutation-tests:
        name: "Mutation tests"
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
        env:
            STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
        steps:
            -   uses: actions/checkout@v4
                with:
                    fetch-depth: 0
            -   name: Setup .NET SDKs
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: |
                        8.0.x
            -   name: Upload mutation dashboard and create comment
                run: ./build.sh MutationTestDashboard
                env:
                    GithubToken: ${{ secrets.GITHUB_TOKEN }}
                    WorkflowRunId: ${{ github.event.workflow_run.id }}
    
    benchmarks:
        name: "Benchmarks"
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        steps:
            -   uses: actions/checkout@v4
                with:
                    fetch-depth: 0
            -   name: Setup .NET SDKs
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: |
                        8.0.x
            -   name: Create benchmark comment
                run: ./build.sh BenchmarkComment
                env:
                    GithubToken: ${{ secrets.GITHUB_TOKEN }}
                    WorkflowRunId: ${{ github.event.workflow_run.id }}
    
    static-code-analysis:
        name: "Static code analysis"
        runs-on: ubuntu-latest
        env:
            REPORTGENERATOR_LICENSE: ${{ secrets.REPORTGENERATOR_LICENSE }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            DOTNET_NOLOGO: true
        steps:
            -   uses: actions/checkout@v4
                with:
                    ref: ${{ github.event.workflow_run.head_branch }}
                    fetch-depth: 0
            -   name: Setup .NET SDKs
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: |
                        8.0.x
            -   name: Run sonarcloud analysis
                run: ./build.sh CodeAnalysis
